version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'

  api:
    image: 'eraarby/multi-server'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    image: 'eraarby/multi-client'
  worker:
    image: 'eraarby/multi-worker'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: 'eraarby/multi-nginx'
    ports:
      - '3050:80'
      - '3443:443'
    restart: always
