apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/app-root: client-cluster-ip-service
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    # - host: default-http-backend
     - http:
          paths:
            # - path:  /api(/|$)(.*)
            - path: /api(/|$)(.*)
              backend:
                serviceName: server-cluster-ip-service
                servicePort: 5000
            - path: /(/*|$)(.*)
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
